### ISSUE TITLE
Stable version?

### ISSUE THREAD

**Issue by TribuneX** [fruux/Baikal2#48]
Is this project still activley developed? There is not much news lately about an upcoming stable release.

**Comment by evert** [comment]
Currently most development is happening in https://github.com/fruux/Baikal, not in the version 2 branch.

**Comment by MarkMaldaba** [comment]
> Currently most development is happening in https://github.com/fruux/Baikal, not in the version 2 branch.

@evert - Given the number of tickets/questions that come up, wouldn't it be a good idea to mention this, really quite prominently, at the top of README.md?

**Comment by evert** [comment]
@MarkMaldaba part of the reason is that I didn't want to overstep my boundaries and thought that maybe the original maintainer would want to pick Baikal 2 up. This hasn't really happened, so yea.. maybe it's a good time to do this.

One question i have is, where did you find this repository? Is still being linked from places or did you just have it bookmarked from a long time ago.

**Comment by MarkMaldaba** [comment]
Personally, I've had it in my watch list for quite a while.  However, there still seem to be new people finding it so it's obviously showing-up somewhere.

**Comment by TribuneX** [comment]
I used Google, since I am aware of v2.

**Comment by evert** [comment]
I updated the main page to say that active development is happening in the other repository.
